### PR TITLE
Removed extra RCTBridge.h

### PR DESCRIPTION
**Pull request by jerson-av**
RCTBridge is duplicated and cause error when build on ios

### CODE REVIEW

**Comment by tangnv** [comment]
Hi @jerson-av, does it work with latest react native version? My iOS app was crashed although Android worked well

**Comment by jerson-av** [comment]
now i'm using my fork https://github.com/jerson-av/react-native-pinch
is a bit different because cert or certs params don't require files, just cert in base64

**Comment by tangnv** [comment]
Let me try, this package works well without cer param

**Comment by tangnv** [comment]
@jerson-av could you update readme file?

**Pull request closed without merging**
